# Generated by Django 5.1.3 on 2024-11-12 17:50

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_additional_images_post_author_post_cover_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='additional_images',
        ),
        migrations.AlterField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.upload_to_cover),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(upload_to=blog.models.upload_to_additional),
        ),
    ]
