# Generated by Django 5.1.3 on 2024-12-03 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_datetime', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='blog.post')),
            ],
            options={
                'verbose_name': 'Post Metric',
                'verbose_name_plural': 'Posts Metrics',
            },
        ),
    ]
