# Generated by Django 5.1.3 on 2024-11-12 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_additional_images_alter_post_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='number_of_visitors',
            field=models.IntegerField(default=0),
        ),
    ]
