# Generated by Django 5.1.3 on 2024-12-04 12:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_postmetrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmetrics',
            name='access_datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
