# Generated by Django 5.1.3 on 2024-12-06 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_like_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='action',
            field=models.CharField(default='', max_length=7),
        ),
    ]
